<?php

return array(
    'name'=>"Contacts",
    'install'=>array(
        'CREATE TABLE x2_contacts(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName VARCHAR(40) NOT NULL,
	lastName VARCHAR(40) NOT NULL,
	title VARCHAR(40),
	company VARCHAR(250),
	phone VARCHAR(40),
	email VARCHAR(250),
	website VARCHAR(250),
	address VARCHAR(250),
	address2 VARCHAR(250),
	city VARCHAR(40),
	state VARCHAR(40),
	zipcode VARCHAR(20),
	country VARCHAR(40),
	visibility INT NOT NULL,
	assignedTo VARCHAR(20),
	backgroundInfo TEXT,
	twitter VARCHAR(20) NULL,
	linkedin VARCHAR(100) NULL,
	skype VARCHAR(32) NULL,
	googleplus VARCHAR(100) NULL,
	lastUpdated VARCHAR(30),
	updatedBy VARCHAR(20),
	priority VARCHAR(40),
	leadSource VARCHAR(40),
	leadDate INT UNSIGNED,
	rating TINYINT,
	createDate INT UNSIGNED,
	facebook VARCHAR(100) NULL,
	otherUrl VARCHAR(100) NULL,
	phone2 VARCHAR(40),
	leadtype VARCHAR(250),
	closedate VARCHAR(250),
	interest VARCHAR(250),
	leadstatus VARCHAR(250),
	dealvalue VARCHAR(250),
	leadscore INT,
	dealstatus VARCHAR(250),
	INDEX (email),
	INDEX (assignedTo)
) COLLATE = utf8_general_ci',
            'INSERT INTO x2_fields (modelName, fieldName, attributeLabel, modified, custom, type, required, linkType) VALUES 
                    ("Contacts",	"id",					"ID",					0,	0,	"varchar",		0,	""),
                    ("Contacts",	"firstName",                            "First Name",                           0,	0,	"varchar",		1,	""),
                    ("Contacts",	"lastName",				"Last Name",                            0,	0,	"varchar",		1,	""),
                    ("Contacts",	"title",				"Title",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"company",				"Account",				0,	0,	"link",			0,	"accounts"),
                    ("Contacts",	"phone",				"Phone",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"phone2",				"Phone 2",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"email",				"Email",				0,	0,	"email",		0,	""),
                    ("Contacts",	"website",				"Website",				0,	0,	"url",			0,	""),
                    ("Contacts",	"twitter",				"Twitter",				0,	0,	"url",                  0,	"twitter"),
                    ("Contacts",	"linkedin",				"Linkedin",				0,	0,	"url",                  0,	"linkedin"),
                    ("Contacts",	"skype",				"Skype",				0,	0,	"url",  		0,	"skype"),
                    ("Contacts",	"googleplus",                           "Googleplus",                           0,	0,	"url",                  0,	"googleplus"),
                    ("Contacts",	"address",				"Address",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"address2",				"Address 2",                            0,	0,	"varchar",		0,	""),
                    ("Contacts",	"city",					"City",					0,	0,	"varchar",		0,	""),
                    ("Contacts",	"state",				"State",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"zipcode",				"Postal Code",                          0,	0,	"varchar",		0,	""),
                    ("Contacts",	"country",				"Country",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"visibility",                           "Visibility",                           0,	0,	"visibility",           1,	""),
                    ("Contacts",	"assignedTo",                           "Assigned To",                          0,	0,	"assignment",           0,	""),
                    ("Contacts",	"backgroundInfo",                       "Background Info",                      0,	0,	"text",			0,	""),
                    ("Contacts",	"lastUpdated",                          "Last Updated",                         0,	0,	"date",			0,	""),
                    ("Contacts",	"updatedBy",                            "Updated By",                           0,	0,	"varchar",		0,	""),
                    ("Contacts",	"leadSource",                           "Lead Source",                          0,	0,	"dropdown",		0,	"4"),
                    ("Contacts",	"leadDate",				"Lead Date",                            0,	0,	"date",			0,	""),
                    ("Contacts",	"priority",				"Priority",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"rating",				"Confidence",                           0,	0,	"rating",		0,	""),
                    ("Contacts",	"createDate",                           "Create Date",                          0,	0,	"date",			0,	""),
                    ("Contacts",	"facebook",				"Facebook",				0,	0,	"url",                  0,	"facebook"),
                    ("Contacts",	"otherUrl",				"Other",				0,	0,	"url",                  0,	""),
                    ("Contacts",	"leadtype",				"Lead Type",                            0,	0,	"dropdown",		0,	"3"),
                    ("Contacts",	"closedate",                            "Close Date",                           0,	0,	"date",			0,	""),
                    ("Contacts",	"interest",				"Interest",				0,	0,	"varchar",		0,	""),
                    ("Contacts",	"dealvalue",                            "Deal Value",                           0,	0,	"currency",		0,	NULL),
                    ("Contacts",	"leadstatus",                           "Lead Status",                          0,	0,	"dropdown",		0,	"5"),
                    ("Contacts",	"leadscore",                            "Lead Score",                           0,	0,	"rating",		0,	NULL),
                    ("Contacts",	"dealstatus",                           "Deal Status",                          0,	0,	"dropdown",		0,	"6");',
    ),
    'uninstall'=>array(
        'DELETE FROM x2_fields WHERE modelName="Contacts"',
        'DROP TABLE x2_contacts',
    ),
    'editable'=>true,
    'searchable'=>true,
    'adminOnly'=>false,
    'custom'=>false,
    'toggleable'=>false,
    
);
?>
