<?php

return array(
    'name'=>"Actions",
    'install'=>array(
        'CREATE TABLE x2_actions(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	assignedTo VARCHAR(20),
	actionDescription text NOT NULL,
	visibility INT NOT NULL,
	associationId INT NOT NULL,
	associationType VARCHAR(20),
	associationName VARCHAR(100),
	dueDate INT,
	showTime TINYINT NOT NULL DEFAULT 0,
	priority VARCHAR(10),
	type VARCHAR(20),
	createDate INT,
	complete VARCHAR(5) default "No",
	reminder VARCHAR(5),
	completedBy VARCHAR(20),
	completeDate INT,
	lastUpdated INT,
	updatedBy VARCHAR(20),
	workflowId INT UNSIGNED,
	stageNumber INT UNSIGNED,
	allDay TINYINT,
	color VARCHAR(20),
	INDEX (assignedTo),
	INDEX (associationType,associationId)
) COLLATE = utf8_general_ci',
            'INSERT INTO x2_fields (modelName, fieldName, attributeLabel, modified, custom, type, required, linkType) VALUES 
                    ("Actions",		"id",					"ID",					0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"assignedTo",                           "Assigned To",                          0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"actionDescription",                    "Description",                          0,	0,	"varchar",		1,	NULL),
                    ("Actions",		"visibility",                           "Visibility",                           0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"associationId",                        "Contact",				0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"associationType",                      "Association Type",                     0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"associationName",                      "Association",                          0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"dueDate",				"Due Date",				0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"priority",				"Priority",				0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"type",					"Action Type",                          0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"createDate",                           "Create Date",                          0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"complete",				"Complete",				0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"reminder",				"Reminder",				0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"completedBy",                          "Completed By",                         0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"completeDate",                         "Date Completed",                       0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"lastUpdated",                          "Last Updated",                         0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"updatedBy",                            "Updated By",                           0,	0,	"varchar",		0,	NULL),
                    ("Actions",		"allDay",				"All Day",				0,	0,	"boolean",		0,	NULL),
                    ("Actions",		"color",				"Color",				0,	0,	"varchar",		0,	NULL);',
    ),
    'uninstall'=>array(
        'DELETE FROM x2_fields WHERE modelName="Actions"',
        'DROP TABLE x2_actions',
    ),
    'editable'=>false,
    'searchable'=>true,
    'adminOnly'=>false,
    'custom'=>false,
    'toggleable'=>false,
    
);
?>
