<?php /* This file is generated by ThemeBuildCommand.php. Do not edit manually */
return "

    /* line 33, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.page-title.{$module} {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
    }

    /* line 35, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.page-title.{$module} .x2-button {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
        ".((isset ($colors["text_{$module}_override"]) && $colors["text_{$module}_override"]) ? "color: {$colors["text_{$module}_override"]}" : "")."
    }

    /* line 39, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.page-title.{$module} > .summary > span + div {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
    }

    /* line 42, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.page-title.{$module} > h2, div.page-title.{$module} > h2 > span, div.page-title.{$module} > .summary > span, div.page-title.{$module} > .summary > span > *, div.page-title.{$module} > .record-aliases-dropdown-container > h2, div.page-title.{$module} > span.icon, div.page-title.{$module} > .vcrPager > .summary {
        ".((isset ($colors["text_{$module}_override"]) && $colors["text_{$module}_override"]) ? "color: {$colors["text_{$module}_override"]}" : "")."
    }

    /* line 53, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
    }

    /* line 55, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} .x2-button, div.widget-title-bar.{$module} .x2-icon-button {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
        ".((isset ($colors["text_{$module}_override"]) && $colors["text_{$module}_override"]) ? "color: {$colors["text_{$module}_override"]}" : "")."
    }

    /* line 59, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} > div {
        ".((isset ($colors["text_{$module}_override"]) && $colors["text_{$module}_override"]) ? "color: {$colors["text_{$module}_override"]}" : "")."
    }

    /* line 62, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} + div .page-title {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
    }

    /* line 64, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} + div .page-title > .summary > span > div {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
    }

    /* line 67, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} + div .page-title > .summary > span, div.widget-title-bar.{$module} + div .page-title > .summary > span > * {
        ".((isset ($colors["text_{$module}_override"]) && $colors["text_{$module}_override"]) ? "color: {$colors["text_{$module}_override"]}" : "")."
    }

    /* line 72, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} + div .page-title .x2-button {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
        ".((isset ($colors["text_{$module}_override"]) && $colors["text_{$module}_override"]) ? "color: {$colors["text_{$module}_override"]}" : "")."
    }

    /* line 77, ../../../compass/themes/x2engine/css/moduleOverrides.scss */
    div.widget-title-bar.{$module} + div .page-title .x2-button:hover, div.widget-title-bar.{$module} + div .page-title .x2-button:active {
        ".((isset ($colors["background_{$module}_override"]) && $colors["background_{$module}_override"]) ? "background-color: {$colors["background_{$module}_override"]}" : "")."
    }

 "; ?>